version: '3.8'

services:
  drupal:
    image: drupal:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      # if you want to bind mount below, you should run the chown command after container is runnning. otherwise you can't install modules
      # chown -R www-data:www-data volumes/drupal
      
      - drupal:/var/www/html
      #- ${VOLUMES_PATH_PREFIX}/drupal/modules:/var/www/html/modules
      #- ${VOLUMES_PATH_PREFIX}/drupal/profiles:/var/www/html/profiles
    restart: always
    user: root
    stdin_open: true
    tty: true

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: drupal-mysql
    restart: always
    stdin_open: true
    tty: true
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  drupal: